### ISSUE TITLE
DOCS formats?

### ISSUE THREAD

**Issue by DanielSchuman** [BadIdeaFactory/demand-editable-drafts#8]
Just a thought. Would using PANDOC or initial representation of this information as markdown make it easier down the line to convert into all sorts of different formats, beyond DOCX like HTML or a future version of docx? This is out of spec, but just thinking down the line for what may make easier for future extensions.

**Comment by knowtheory** [comment]
Unfortunately [pandoc can't turn PDFs into markdown](https://groups.google.com/forum/#!topic/pandoc-discuss/qN71bny2L-Y).

There are a few other tools, like pdftohtml, but conversion into something editable still requires some sort of mapping into docx format.
